apiVersion: v1
kind: Service
metadata:
  name: etcd-k8s
  namespace: kube-system
  labels:
    k8s-app: etcd
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: api
    port: 2379
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: etcd-k8s
  namespace: kube-system
  labels:
    k8s-app: etcd
subsets:
- addresses:
  - ip: 10.1.113.135
    nodeName: etcd1
  - ip: 10.1.113.4
    nodeName: etcd2
  - ip: 10.1.113.248
    nodeName: etcd3
  ports:
  - name: api
    port: 2379
    protocol: TCP